### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:

### ISSUE THREAD

**Issue by Choon-Spring** [xthan/polyvore#4]
Hi,
Thank you for your contribution.

I have this problem. 

```
./extract_feature.sh

Traceback (most recent call last):
  File "polyvore/run_inference_siamese.py", line 90, in <module>
    tf.app.run()
  File "/Users/THEO/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "polyvore/run_inference_siamese.py", line 76, in main
    image_feed = f.read()
  File "/Users/THEO/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/Users/THEO/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Users/THEO/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: data/images/test_no_dup/119704139/1.jpg; No such file or directory
```

I already have 'data/images/test_no_dup/119704139/1.jpg'  
How can I solve this? I want to get helpful information.

**Comment by xthan** [comment]
you need to download the images and put them in the ./data folder

**Comment by xthan** [comment]
If you have already downloaded the image, there should not be any problem. Is the image corupted? I have never met this problem before.

**Comment by Choon-Spring** [comment]
Thank you for your answer. I resolved my problem. Just my mistake :)

**Comment by anorthman** [comment]
I have a similar problem.
File "/home/robot/.local/lib/python3.5/site-packages/tensorflow/models/object_detection/train.py", line 163, in <module>
    tf.app.run()
  File "/home/robot/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/robot/.local/lib/python3.5/site-packages/tensorflow/models/object_detection/train.py", line 106, in main
    overwrite=True)
  File "/home/robot/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 385, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/home/robot/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
How did you solve your problem?

**Comment by hector-m** [comment]
@theopillow I am having the same problem. How did you fix this?
